Repository jellyfin/jellyfin-roku, pull requests merged in 2023-11, with the labels that each got.

#1461 Create pause menu
  components/Clock.bs
  components/Clock.xml
  components/ItemGrid/LoadVideoContentTask.brs
  components/video/PauseMenu.bs
  components/video/PauseMenu.xml
  components/video/VideoPlayerView.brs
  components/video/VideoPlayerView.xml
  images/icons/nextChapter.png
  images/icons/numberList.png
  images/icons/pause.png
  images/icons/previousChapter.png
  images/icons/subtitle.png
  images/icons/videoInfo.png
  locale/en_US/translations.ts
  source/api/Items.brs
Labels: new-feature

#1470 Show loading spinner and disable remote during login
  source/Main.brs
  source/ShowScenes.brs
Labels: new-feature

#1475 Fix registry migration for next release
  source/migrations.bs
Labels: ignore-changelog

#1462 Create and use generic PostTask to post device profile
  components/data/SceneManager.brs
  components/home/Home.brs
  components/home/Home.xml
  components/settings/settings.brs
  components/settings/settings.xml
  components/tasks/PostTask.bs
  components/tasks/PostTask.xml
  source/Main.brs
  source/VideoPlayer.brs
  source/api/baserequest.brs
  source/utils/deviceCapabilities.brs
  source/utils/session.bs
Labels: code-cleanup

#1490 Add general-improvement label to auto generated changelog
  .github/release.yml
Labels: ignore-changelog

#1489 Save credentials if asked when using quick connect
  components/quickConnect/QuickConnectDialog.bs
  components/quickConnect/QuickConnectDialog.xml
  source/ShowScenes.bs
Labels: bug-fix

#1491 Add progress bar to pause menu
  components/music/AudioPlayerView.bs
  components/video/PauseMenu.bs
  components/video/PauseMenu.xml
  components/video/VideoPlayerView.bs
  source/utils/misc.bs
Labels: new-feature

#1494 Fix photo regression, add photo support to home screen, and add quickplay photo support
  components/ItemGrid/ItemGrid.bs
  components/data/HomeData.bs
  components/home/Home.bs
  components/home/HomeItem.bs
  components/home/HomeRows.bs
  components/photos/LoadPhotoTask.bs
  components/photos/LoadPhotoTask.xml
  components/photos/PhotoDetails.bs
  components/photos/PhotoDetails.xml
  source/Main.bs
  source/utils/misc.bs
  source/utils/quickplay.bs
Labels: new-feature

#1506 Prevent pause menu if video isn't in a ready state
  components/video/VideoPlayerView.bs
Labels: bug-fix

#1507 Rename pauseMenu component to OSD
  components/video/OSD.bs
  components/video/OSD.xml
  components/video/VideoPlayerView.bs
  components/video/VideoPlayerView.xml
  locale/en_US/translations.ts
Labels: code-cleanup

#1502 Fix user registry migration logic + print out registry when asked
  manifest
  source/Main.bs
  source/migrations.bs
  source/utils/conditional.bs
  source/utils/config.bs
  source/utils/session.bs
Labels: dev-improvement

#1510 Fix migration crash
  source/migrations.bs
Labels: bug-fix

#1512 Increase font size for unwatched episode count
  components/ItemGrid/GridItem.xml
  components/ListPoster.xml
  components/home/HomeItem.xml
  components/tvshows/TVEpisodes.xml
  components/tvshows/TVShowDetails.xml
Labels: general-improvement

#1518 Don't show nextEpisode button if trickplay bar is shown
  components/video/VideoPlayerView.bs
Labels: bug-fix

#1513 Fix episode list bug where OK was triggering quickplay
  components/tvshows/TVEpisodes.bs
  components/tvshows/TVEpisodes.xml
  source/ShowScenes.bs
Labels: bug-fix

#1529 Fix TV Guide bug
  components/ItemGrid/ItemGrid.bs
Labels: bug-fix

#1532 Fix remember me bug
  components/data/UserData.bs
  components/data/UserData.xml
  source/api/userauth.bs
  source/utils/session.bs
Labels: bug-fix

#1535 Use `type=module` in package.json
  package.json
  scripts/ropm-hook.cjs
Labels: dev-improvement

#1515 Convert app to use one spinner attached to JFScene + resize spinner
  components/ItemGrid/ItemGrid.bs
  components/ItemGrid/ItemGrid.xml
  components/ItemGrid/MovieLibraryView.bs
  components/ItemGrid/MovieLibraryView.xml
  components/ItemGrid/MusicLibraryView.bs
  components/ItemGrid/MusicLibraryView.xml
  components/JFScene.bs
  components/JFScene.xml
  components/Spinner.bs
  components/config/SetServerScreen.bs
  components/config/SetServerScreen.xml
  components/liveTv/schedule.bs
  components/liveTv/schedule.xml
  components/login/UserSelect.bs
  components/movies/MovieDetails.bs
  components/movies/MovieDetails.xml
  components/music/AlbumView.bs
  components/music/AlbumView.xml
  components/music/ArtistView.bs
  components/music/AudioPlayerView.bs
  components/music/PlaylistView.bs
  components/music/PlaylistView.xml
  components/photos/PhotoDetails.bs
  components/search/SearchResults.bs
  components/search/SearchResults.xml
  components/video/VideoPlayerView.bs
  images/spinner.png
  source/Main.bs
  source/ShowScenes.bs
  source/VideoPlayer.bs
  source/utils/misc.bs
  source/utils/quickplay.bs
Labels: general-improvement
