Repository jellyfin/jellyfin-roku, pull requests merged in 2023-12, with the labels that each got.

#1549 Fix infinite spinner bugs
  components/ItemGrid/ItemGrid.bs
  components/ItemGrid/MovieLibraryView.bs
  components/ItemGrid/MusicLibraryView.bs
  components/data/SceneManager.bs
Labels: bug-fix

#1559 Fix focus on library row
  components/home/HomeRows.bs
Labels: bug-fix

#1585 sync branches
  .github/workflows/automations.yml
  .github/workflows/build-dev.yml
  .github/workflows/build-docs.yml
  .github/workflows/build-prod.yml
  .github/workflows/deploy-api-docs.yml
  .github/workflows/lint.yml
  .github/workflows/release-prep.yml
Labels: ignore-changelog

#1574 Fix migration crash
  source/migrations.bs
Labels: bug-fix

#1517 Add Random sorting to supported libraries
  components/ItemGrid/ItemGrid.bs
  components/ItemGrid/MovieLibraryView.bs
  components/ItemGrid/MusicLibraryView.bs
  locale/en_US/translations.ts
Labels: new-feature

#1597 Fix selecting episode using OK button on episode list view
  components/tvshows/TVEpisodes.bs
  source/ShowScenes.bs
Labels: bug-fix
