Repository jellyfin/jellyfin-roku, pull requests merged in 2023-02, with the labels that each got.

#998 options button closes user settings menu
  components/settings/settings.brs
Labels: needs work

#918 Install & Configure unit test suite
  bsconfig.json
  source/Main.brs
  source/testFramework/UnitTestFramework.brs
  source/tests/Test__Misc.brs
Labels: ready for review

#1013 Create Setting for Next Episode Button Time
  components/JFVideo.brs
  locale/en_US/translations.ts
  settings/settings.json
Labels: needs work

#982 Change subtitle renderer from Roku embedded to a custom task
  components/JFVideo.brs
  components/JFVideo.xml
  components/captionTask.brs
  components/captionTask.xml
  locale/en_US/translations.ts
  settings/settings.json
  source/Main.brs
  source/utils/Subtitles.brs
Labels: enhancement

#1033 Add workflow to validate XML translation files
  .github/workflows/lint.yml
  .github/workflows/validate.yml
  .vscode/extensions.json
  .vscode/settings.json
  locale/bg/translations.ts
  locale/cs/translations.ts
  locale/de_DE/translations.ts
  locale/en_GB/translations.ts
  locale/es_419/translations.ts
  locale/es_AR/translations.ts
  locale/es_ES/translations.ts
  locale/fr/translations.ts
  locale/fr_CA/translations.ts
  locale/hu/translations.ts
  locale/it_IT/translations.ts
  locale/lv/translations.ts
  locale/pt_BR/translations.ts
  locale/ro/translations.ts
  locale/sk/translations.ts
  locale/sl/translations.ts
  locale/zu/translations.ts
Labels: ready for review

#986 Playlist support & TV Shuffle
  components/GetPlaybackInfoTask.brs
  components/GetPlaybackInfoTask.xml
  components/GetShuffleEpisodesTask.brs
  components/GetShuffleEpisodesTask.xml
  components/ItemGrid/GridItem.brs
  components/ItemGrid/LoadItemsTask2.brs
  components/ItemGrid/LoadVideoContentTask.brs
  components/ItemGrid/LoadVideoContentTask.xml
  components/RadioDialog.brs
  components/RadioDialog.xml
  components/StandardDialog.brs
  components/StandardDialog.xml
  components/data/PlaylistData.brs
  components/data/PlaylistData.xml
  components/data/SceneManager.brs
  components/data/SceneManager.xml
  components/manager/QueueManager.brs
  components/manager/QueueManager.xml
  components/manager/ViewCreator.brs
  components/music/AudioPlayerView.brs
  components/music/PlaylistView.brs
  components/music/PlaylistView.xml
  components/tvshows/TVEpisodes.brs
  components/tvshows/TVEpisodes.xml
  components/tvshows/TVShowDetails.brs
  components/tvshows/TVShowDetails.xml
  components/video/VideoPlayerView.brs
  components/video/VideoPlayerView.xml
  source/Main.brs
  source/ShowScenes.brs
  source/api/Items.brs
  source/api/constants.brs
  source/utils/misc.brs
Labels: ready for review

#928 Add Genres, Parental Ratings, and Years as Movie Filters
  components/ItemGrid/ItemGridOptions.brs
  components/ItemGrid/ItemGridOptions.xml
  components/ItemGrid/LoadItemsTask2.brs
  components/ItemGrid/LoadItemsTask2.xml
  components/ItemGrid/MovieLibraryView.brs
  components/ItemGrid/MovieLibraryView.xml
  components/data/GetFiltersTask.brs
  components/data/GetFiltersTask.xml
  components/options/OptionNode.brs
  components/options/OptionNode.xml
  locale/en_US/translations.ts
  source/utils/misc.brs
Labels: ready for review

#1024 Create global audio player
  components/mediaPlayers/AudioPlayer.brs
  components/mediaPlayers/AudioPlayer.xml
  components/music/AudioPlayerView.brs
  components/music/AudioPlayerView.xml
  source/Main.brs
Labels: enhancement, ready for review
