Repository jellyfin/jellyfin-roku, pull requests merged in 2024-08, with the labels that each got.

#1872 Fix ExtrasItem crash
  components/extras/ExtrasItem.bs
Labels: bug-fix

#1875 Remove unneeded API call and fix LoadVideoContentTask crash (2)
  components/ItemGrid/LoadVideoContentTask.bs
Labels: bug-fix

#1890 Fix home item poster and progress bar alignment
  components/home/HomeItem.xml
Labels: bug-fix

#1871 Fix GridItem crash
  components/ItemGrid/GridItem.bs
  components/ItemGrid/ItemGrid.bs
  components/ItemGrid/ItemGrid.xml
Labels: bug-fix

#1874 Remove unneeded API call and fix LoadVideoContentTask crash
  components/ItemGrid/LoadVideoContentTask.bs
Labels: bug-fix

#1879 Create `Episode Image Next Up` user setting
  components/home/HomeItem.bs
  locale/en_US/translations.ts
  settings/settings.json
  source/utils/misc.bs
  source/utils/session.bs
Labels: new-setting

#1895 Play Song as Part of a Playlist
  source/Main.bs
Labels: general-improvement

#1898 Update master with 2.1.4 bugfixes
  Makefile
  components/ItemGrid/GridItem.bs
  components/ItemGrid/ItemGrid.bs
  components/ItemGrid/ItemGrid.xml
  components/ItemGrid/ItemGridOptions.bs
  components/ItemGrid/LoadVideoContentTask.bs
  components/extras/ExtrasItem.bs
  components/home/HomeItem.bs
  components/home/HomeItem.xml
  manifest
  package-lock.json
  package.json
  source/Main.bs
  source/ShowScenes.bs
  source/api/Items.bs
Labels: ignore-changelog
