Repository jellyfin/jellyfin-roku, pull requests merged in 2024-09, with the labels that each got.

#1906 Fix: Add Played Indicator to Series
  components/data/HomeData.bs
Labels: general-improvement

#1900 Fix View All Next Up crash
  components/ItemGrid/GridItem.bs
Labels: bug-fix

#1881 Create `Play Next Episode Automatically` user setting
  components/ItemGrid/LoadVideoContentTask.bs
  components/JFVideo.bs
  components/video/VideoPlayerView.bs
  locale/en_US/translations.ts
  settings/settings.json
  source/VideoPlayer.bs
Labels: new-setting

#1869 Add new vscode launch option to deploy app without building
  .vscode/launch.json
Labels: dev-improvement

#1931 Fix for disappearing titles
  components/ItemGrid/GridItem.bs
Labels: bug-fix

#1936 Allow for LiveTV remux from server
  components/data/ChannelData.xml
  source/api/Items.bs
Labels: bug-fix

#1928 Fix AAC codec support - Stop trying to direct play profile "main"
  source/utils/deviceCapabilities.bs
Labels: bug-fix

#1896 Fix ItemGrid backdrop when alpha is active and prevent loading background twice on first load
  components/ItemGrid/ItemGrid.bs
  components/ItemGrid/ItemGrid.xml
  images/1px-262626.png
Labels: bug-fix

#1939 Fix incorrect data type being passed to `OverviewDialog.Overview`
  components/music/AlbumView.bs
  components/music/ArtistView.bs
  components/music/PlaylistView.bs
Labels: code-cleanup

#1941 Update server when video is in state `finished`
  components/PlaystateTask.bs
  components/video/VideoPlayerView.bs
Labels: bug-fix

#1942 Update master with fixes from v2.1.5
  Makefile
  components/ItemGrid/GridItem.bs
  components/ItemGrid/ItemGrid.bs
  components/ItemGrid/ItemGrid.xml
  components/PlaystateTask.bs
  components/data/ChannelData.xml
  components/video/VideoPlayerView.bs
  images/1px-262626.png
  manifest
  package-lock.json
  package.json
  source/api/Items.bs
  source/utils/deviceCapabilities.bs
Labels: ignore-changelog

#1946 Disable `playback.bitrate.maxlimited` by default
  settings/settings.json
Labels: general-improvement
