Repository jellyfin/jellyfin-roku, pull requests merged in 2024-11, with the labels that each got.

#2020 Fix forced subs keep Roku subs set to "On Always"
  components/video/VideoPlayerView.bs
Labels: bug-fix

#2026 Fix sorting by Date Played when viewing a TV Show library
  components/ItemGrid/ItemGrid.bs
Labels: bug-fix

#2017 Include Channel Number with Live TV Channels
  components/data/ChannelData.bs
  locale/en_US/translations.ts
Labels: general-improvement

#2027 Merge 2.2.2 into master
  Makefile
  components/ItemGrid/ItemGrid.bs
  components/video/VideoPlayerView.bs
  manifest
  package-lock.json
  package.json
Labels: ignore-changelog

#2029 Fix crash on home screen
  components/home/HomeItem.bs
Labels: bug-fix

#2032 Add Live TV Series Title, Season Number, and Episode Number to OSD
  components/ItemGrid/LoadVideoContentTask.bs
  components/video/VideoPlayerView.bs
Labels: general-improvement

#1891 Expand home rows to take up full width of the screen
  components/home/HomeRows.bs
  locale/en_US/translations.ts
  settings/settings.json
Labels: new-setting

#2034 Fix crash on episode list when video codec is invalid
  components/tvshows/TVListDetails.bs
  locale/en_US/translations.ts
Labels: bug-fix

#2039 Merge 2.2.3 into master
  Makefile
  components/home/HomeItem.bs
  components/tvshows/TVListDetails.bs
  locale/en_US/translations.ts
  manifest
  package-lock.json
  package.json
Labels: ignore-changelog

#2038 Alphabetize all user settings
  settings/settings.json
Labels: general-improvement

#2044 Improve AV1 support - Fix direct streaming with no sound
  source/utils/deviceCapabilities.bs
Labels: bug-fix

#2050 Subtitle should be on when a default one has been selected by the user.
  components/video/VideoPlayerView.bs
Labels: bug-fix

#2035 Fix Continue Watching row index when home screen is refreshed
  components/home/HomeRows.bs
Labels: bug-fix

#2041 Make settings menu wrap around
  components/settings/settings.bs
Labels: general-improvement

#2053 Merge 2.2.4 into master
  Makefile
  components/home/HomeRows.bs
  components/video/VideoPlayerView.bs
  manifest
  package-lock.json
  package.json
  source/utils/deviceCapabilities.bs
Labels: ignore-changelog

#2055 Force mp3 when playback fails because of unsupported aac stream
  components/ItemGrid/LoadVideoContentTask.bs
  components/ItemGrid/LoadVideoContentTask.xml
  components/video/VideoPlayerView.bs
  components/video/VideoPlayerView.xml
  source/api/Items.bs
Labels: bug-fix

#2046 Enable OSD for intro videos
  components/video/VideoPlayerView.bs
Labels: general-improvement

#2063 Validate dependency PRs
  .github/workflows/_build-dev.yml
  .github/workflows/_build-prod.yml
  .github/workflows/_lint-brightscript.yml
  .github/workflows/_lint-json.yml
  .github/workflows/_lint-markdown.yml
  .github/workflows/_lint-spelling.yml
  .github/workflows/_lint-translation-files.yml
  .github/workflows/_roku-analysis.yml
  .github/workflows/_validate-dependencies.yml
  .github/workflows/build-dev.yml
  .github/workflows/build-prod.yml
  .github/workflows/dependencies.yml
  .github/workflows/lint-brightscript.yml
  .github/workflows/lint-json.yml
  .github/workflows/lint-markdown.yml
  .github/workflows/lint-spelling.yml
  .github/workflows/lint-translation-files.yml
  .github/workflows/roku-analysis.yml
Labels: dev-improvement

#2069 Make all jobs run for a dependency PR
  .github/workflows/_build-dev.yml
  .github/workflows/_build-prod.yml
  .github/workflows/_roku-analysis.yml
  .github/workflows/_validate-dependencies.yml
  .github/workflows/build-dev.yml
  .github/workflows/roku-analysis.yml
Labels: ignore-changelog
