Repository jellyfin/jellyfin-roku, pull requests merged in 2024-01, with the labels that each got.

#1547 Add watched checkmark to Movies, Collections, TV Shows, Season list. Remove API generated checkmark
  components/ItemGrid/GridItem.bs
  components/ItemGrid/GridItem.xml
  components/ItemGrid/GridItemSmall.bs
  components/ItemGrid/GridItemSmall.xml
  components/ListPoster.bs
  components/ListPoster.xml
  source/api/Items.bs
Labels: general-improvement

#1608 Fix subtitle selection for subtitles that are not encoded
  components/manager/ViewCreator.bs
  components/video/VideoPlayerView.bs
Labels: bug-fix

#1594 Rework OSD clock to support legacy devices
  components/Clock.bs
Labels: bug-fix

#1603 Make music artist presentation views honor the Item Titles setting
  components/ItemGrid/MusicLibraryView.bs
Labels: bug-fix

#1600 Fix launching Live TV channels from outside the guide
  components/ItemGrid/LoadVideoContentTask.bs
Labels: bug-fix

#1610 Bump version for release
  Makefile
  manifest
  package.json
Labels: release-prep

#1604 Fix default subtitle track selection
  components/ItemGrid/LoadVideoContentTask.bs
  components/ItemGrid/LoadVideoContentTask.xml
  components/video/VideoPlayerView.bs
  components/video/VideoPlayerView.xml
Labels: bug-fix

#1618 bump version of bugfix branch
  Makefile
  manifest
  package.json
Labels: ignore-changelog, release-prep

#1633 Allow subtitles to have more than 1 type
  components/ItemGrid/LoadVideoContentTask.bs
Labels: bug-fix

#1641 Allow default subtitles to enable global caption mode
  components/video/VideoPlayerView.bs
Labels: bug-fix

#1632 Prevent unneeded video stop/start when turning off text subtitles
  components/manager/ViewCreator.bs
  components/video/VideoPlayerView.bs
  components/video/VideoPlayerView.xml
Labels: bug-fix

#1640 Fix saved credentials when using multiple users
  source/ShowScenes.bs
  source/utils/session.bs
Labels: bug-fix

#1646 Fix song data out of sync if changing songs quickly
  components/music/AudioPlayerView.bs
Labels: bug-fix

#1651 Fix QuickConnect
  components/quickConnect/QuickConnect.bs
  components/quickConnect/QuickConnect.xml
  components/quickConnect/QuickConnectDialog.bs
Labels: bug-fix

#1645 Fix sporadic crash on home screen
  components/home/HomeItem.bs
Labels: bug-fix

#1656 bump bugfix branch version
  Makefile
  manifest
  package.json
Labels: ignore-changelog, release-prep

#1653 Label actor episodes with series name, and season & episode numbers
  components/extras/ExtrasRowList.bs
  source/utils/misc.bs
Labels: general-improvement

#1671 Fix no audio stream crash
  components/ItemGrid/LoadVideoContentTask.bs
Labels: bug-fix

#1522 Add audio track selection to video player OSD
  components/ItemGrid/LoadVideoContentTask.bs
  components/RadioDialog.bs
  components/manager/ViewCreator.bs
  components/video/OSD.xml
  components/video/VideoPlayerView.bs
  components/video/VideoPlayerView.xml
  images/icons/musicNote.png
Labels: new-feature

#1622 Add scrub function to audio trickplay bar
  components/music/AudioPlayerView.bs
  components/music/AudioPlayerView.xml
  images/icons/circle.png
Labels: new-feature
