Repository jellyfin/jellyfin-roku, pull requests merged in 2024-07, with the labels that each got.

#1790 Update master branch with new bugfixe
  .github/workflows/roku-analysis.yml
  Makefile
  bsconfig-tdd-sample.json
  bsconfig-tests.json
  components/WhatsNewDialog.bs
  components/home/HomeRows.bs
  components/login/UserItem.xml
  components/manager/QueueManager.bs
  components/movies/MovieDetails.bs
  components/movies/MovieDetails.xml
  components/tvshows/TVEpisodes.bs
  components/tvshows/TVEpisodes.xml
  components/tvshows/TVListDetails.bs
  locale/en_US/translations.ts
  manifest
  package-lock.json
  package.json
  source/Main.bs
  source/ShowScenes.bs
  source/static/whatsNew/2.0.0.json
  source/static/whatsNew/2.0.1.json
  source/static/whatsNew/2.0.2.json
  source/static/whatsNew/2.0.3.json
  source/static/whatsNew/2.0.4.json
  source/utils/misc.bs
  test-app/source/tests/utils/misc/isAllValid.spec.bs
  test-app/source/tests/utils/misc/isChainValid.spec.bs
Labels: ignore-changelog

#1539 Update Alpha menu - refactor, bugfix, and QOL updates
  components/ItemGrid/Alpha.bs
  components/ItemGrid/Alpha.xml
  components/ItemGrid/ItemGrid.bs
  components/ItemGrid/ItemGrid.xml
  components/ItemGrid/MovieLibraryView.bs
  components/ItemGrid/MovieLibraryView.xml
  components/ItemGrid/MusicLibraryView.bs
  components/ItemGrid/MusicLibraryView.xml
Labels: general-improvement

#1825 Update dev guide with info about bugfix branch
  docs/DEVGUIDE.md
Labels: documentation

#1828 Update master with 2.0.8 bugfixes
  Makefile
  manifest
  package-lock.json
  package.json
  source/api/UserLibrary.bs
Labels: ignore-changelog

#1833 Prevent app crash when refreshing movie detail screen
  source/Main.bs
Labels: bug-fix

#1834 Prevent app crash when refreshing movie detail screen
  source/Main.bs
Labels: bug-fix

#1837 Fix app crashes when refreshing episode list view
  source/Main.bs
Labels: bug-fix

#1840 Update master with new bugfixes
  Makefile
  manifest
  package-lock.json
  package.json
  source/Main.bs
Labels: ignore-changelog

#1792 Add setting to enable rewatching in the "Next Up" section
  components/home/LoadItemsTask.bs
  locale/en_US/translations.ts
  settings/settings.json
  source/utils/quickplay.bs
Labels: new-setting

#1843 Fix invalid movie data crash
  components/data/MovieData.bs
Labels: bug-fix

#1844 Fix invalid episode data crash
  components/data/TVEpisodeData.bs
Labels: bug-fix

#1845 Fix app crash when refreshing episode list view
  source/Main.bs
Labels: bug-fix

#1847 Update master with bugfixes from 2.1.2
  Makefile
  components/data/MovieData.bs
  components/data/TVEpisodeData.bs
  manifest
  package-lock.json
  package.json
  source/Main.bs
Labels: ignore-changelog

#1849 Remove outdated release-prep workflow
  .github/workflows/release-prep.yml
Labels: dev-improvement

#1853 Workflow housekeeping
  .github/workflows/auto-close-stale-pr.yml
  .github/workflows/bump-version.yml
  .github/workflows/lint-brightscript.yml
  .github/workflows/lint-json.yml
  .github/workflows/lint-markdown.yml
  .github/workflows/lint-spelling.yml
  .github/workflows/lint-translation-files.yml
  .github/workflows/lint.yml
  .github/workflows/roku-analysis.yml
Labels: dev-improvement

#1859 Fix ListPoster crash
  components/ListPoster.bs
Labels: bug-fix

#1857 Fix movie library crash
  components/ItemGrid/MovieLibraryView.bs
Labels: bug-fix

#1858 Fix crash on user selection screen
  source/ShowScenes.bs
Labels: bug-fix

#1852 Prevent workflow jobs from running twice
  .github/workflows/automations.yml
  .github/workflows/build-dev.yml
  .github/workflows/roku-analysis.yml
Labels: dev-improvement

#1867 Fix video player crash
  components/video/VideoPlayerView.bs
Labels: bug-fix

#1868 Fix video player crash (2)
  components/video/VideoPlayerView.bs
Labels: bug-fix

#1866 Fix MovieDetails crash (3)
  components/movies/MovieDetails.bs
Labels: bug-fix

#1865 Fix MovieDetails crash (2)
  components/movies/MovieDetails.bs
Labels: bug-fix

#1864 Fix MovieDetails crash
  components/movies/MovieDetails.bs
Labels: bug-fix

#1870 Fix home page crash
  components/home/HomeItem.bs
Labels: bug-fix

#1876 Merge 2.1.3 bugfixes into master
  Makefile
  components/ItemGrid/MovieLibraryView.bs
  components/ListPoster.bs
  components/home/HomeItem.bs
  components/movies/MovieDetails.bs
  components/video/VideoPlayerView.bs
  manifest
  package-lock.json
  package.json
  source/ShowScenes.bs
Labels: ignore-changelog

#1846 Add View All for Next Up
  components/ItemGrid/GridItem.bs
  components/ItemGrid/ItemGrid.bs
  components/ItemGrid/LoadItemsTask2.bs
  components/data/HomeData.bs
  components/home/LoadItemsTask.bs
  locale/en_US/translations.ts
  source/Main.bs
Labels: new-feature

#1880 Fix debug warning when opening the settings page
  components/settings/settings.xml
Labels: code-cleanup

#1886 Fix home page crash (2)
  components/home/HomeItem.bs
Labels: bug-fix

#1887 Fix ItemGrid crash
  components/ItemGrid/ItemGrid.bs
Labels: bug-fix

#1888 Fix ItemGridOptions crash
  components/ItemGrid/ItemGridOptions.bs
Labels: bug-fix

#1885 Fix `ItemMetaData()` crash
  source/api/Items.bs
Labels: bug-fix

#1884 Fix search page crash
  source/api/Items.bs
Labels: bug-fix

#1889 Fix crash on episode list
  source/Main.bs
  source/ShowScenes.bs
Labels: bug-fix

#1873 Fix LoadVideoContentTask crash
  components/ItemGrid/LoadVideoContentTask.bs
Labels: bug-fix
