Repository jellyfin/jellyfin-roku, pull requests merged in 2024-10, with the labels that each got.

#1949 Prevent app crash on home screen
  components/home/HomeItem.bs
Labels: bug-fix

#1948 Prevent app crash when reloading movie details
  source/Main.bs
Labels: bug-fix

#1953 Prevent crash when hitting play from movie details
  source/Main.bs
Labels: bug-fix

#1954 Prevent crash on TV show page when shuffling
  components/tvshows/TVShowDetails.bs
Labels: bug-fix

#1956 Prevent crash on `GridItemSmall`
  components/ItemGrid/GridItemSmall.bs
Labels: bug-fix

#1955 Prevent home screen crash. Validate user setting data
  components/home/HomeItem.bs
Labels: bug-fix

#1952 Prevent crash when refreshing movie details
  source/Main.bs
Labels: bug-fix

#1959 Prevent crash when video path is invalid
  components/ItemGrid/LoadVideoContentTask.bs
  source/VideoPlayer.bs
Labels: bug-fix

#1958 Prevent crash when viewing person details
  components/data/PersonData.bs
Labels: bug-fix

#1957 Prevent crash on music artist grid view
  components/ItemGrid/MusicArtistGridItem.bs
Labels: bug-fix

#1963 Fix AAC codec support for real. Transcode `Main` and `HE-AAC`
  components/ItemGrid/LoadVideoContentTask.bs
  components/video/VideoPlayerView.bs
  source/api/Items.bs
  source/utils/deviceCapabilities.bs
  source/utils/session.bs
Labels: bug-fix

#1964 Prevent crash and Update video player meta data
  components/ItemGrid/LoadVideoContentTask.bs
  source/api/Items.bs
Labels: bug-fix

#1950 Prevent subtitle timeout crash
  components/captionTask.bs
Labels: bug-fix

#1965 Merge 2.1.6 into master
  Makefile
  components/ItemGrid/GridItemSmall.bs
  components/ItemGrid/LoadVideoContentTask.bs
  components/ItemGrid/MusicArtistGridItem.bs
  components/captionTask.bs
  components/data/PersonData.bs
  components/home/HomeItem.bs
  components/tvshows/TVShowDetails.bs
  components/video/VideoPlayerView.bs
  manifest
  package-lock.json
  package.json
  source/Main.bs
  source/VideoPlayer.bs
  source/api/Items.bs
  source/utils/deviceCapabilities.bs
  source/utils/session.bs
Labels: ignore-changelog

#1938 Prevent type mismatch crash
  source/api/sdk.bs
Labels: code-cleanup

#1972 Merge 2.1.7 into master
  Makefile
  components/ItemGrid/LoadVideoContentTask.bs
  manifest
  package-lock.json
  package.json
Labels: ignore-changelog

#1976 Merge 2.1.7 into master
  components/ItemGrid/LoadVideoContentTask.bs
Labels: ignore-changelog

#1982 Prevent crash when there are no media streams
  source/api/Items.bs
Labels: bug-fix

#1989 Improve direct play support for HDR files
  source/utils/deviceCapabilities.bs
  source/utils/globals.bs
Labels: bug-fix

#1990 Merge 2.1.8 into master
  Makefile
  manifest
  package-lock.json
  package.json
  source/api/Items.bs
  source/utils/deviceCapabilities.bs
  source/utils/globals.bs
Labels: ignore-changelog

#1726 Replace Special episode number with "Special" in TvListDetails
  components/tvshows/TVListDetails.bs
  locale/en_US/translations.ts
Labels: general-improvement

#1882 Only show Whats New popup and update lastRunVersion on prod
  source/Main.bs
Labels: dev-improvement

#1945 Save global refs to prevent deep copies
  components/ItemGrid/GridItem.bs
  components/ItemGrid/ItemGrid.bs
  components/ItemGrid/LoadVideoContentTask.bs
  components/ItemGrid/MovieLibraryView.bs
  components/ItemGrid/MusicLibraryView.bs
  components/JFVideo.bs
  components/ListPoster.bs
  components/WhatsNewDialog.bs
  components/home/HomeItem.bs
  components/home/HomeRows.bs
  components/home/LoadItemsTask.bs
  components/manager/ViewCreator.bs
  components/movies/MovieDetails.bs
  components/music/AudioPlayerView.bs
  components/photos/PhotoDetails.bs
  components/settings/settings.bs
  components/tvshows/TVListDetails.bs
  components/tvshows/TVShowDetails.bs
  components/video/OSD.bs
  components/video/VideoPlayerView.bs
Labels: general-improvement

#1995 Prevent crash when audio codec is invalid
  source/api/Items.bs
Labels: bug-fix

#1994 Don't show resumable items in Next Up
  components/home/LoadItemsTask.bs
Labels: bug-fix

#2001 Improve Direct Play support for AV1 codec
  source/utils/deviceCapabilities.bs
Labels: bug-fix
