Repository jellyfin/jellyfin-roku, pull requests merged in 2024-03, with the labels that each got.

#1716 Include special characters when filtering by #
  components/ItemGrid/LoadItemsTask2.bs
Labels: new-feature

#1674 Create popup with full TV series description
  components/StandardDialog.bs
  components/tvshows/TVShowDetails.bs
  locale/en_US/translations.ts
Labels: new-feature

#1740 Fix order of latest in rows on home view
  components/home/HomeRows.bs
Labels: bug-fix

#1672 Add logo and season/episode numbers to OSD
  components/ItemGrid/LoadVideoContentTask.bs
  components/video/OSD.bs
  components/video/OSD.xml
  components/video/VideoPlayerView.bs
  images/osdBackground.png
Labels: new-feature

#1702 Add a new option to select preferred audio codec for transcodes
  locale/en_US/translations.ts
  settings/settings.json
  source/utils/deviceCapabilities.bs
Labels: new-setting

#1749 Update TV Season view data when user goes back to page from Video Player
  components/tvshows/TVEpisodes.bs
  components/tvshows/TVEpisodes.xml
  components/tvshows/TVListDetails.bs
  source/Main.bs
  source/ShowScenes.bs
Labels: bug-fix
