Repository jellyfin/jellyfin-roku, pull requests merged in 2024-04, with the labels that each got.

#1758 Fix screenshot make target
  Makefile
Labels: dev-improvement

#1747 Add scenegraph inspector code
  .vscode/launch.json
  source/Main.bs
Labels: dev-improvement

#1771 Refresh movie detail screen
  components/movies/MovieDetails.bs
  components/movies/MovieDetails.xml
  source/Main.bs
  source/ShowScenes.bs
Labels: bug-fix

#1773 Fix roku static analysis workflow
  .github/workflows/roku-analysis.yml
Labels: dev-improvement

#1774 Make What's New dialog static
  components/WhatsNewDialog.bs
  locale/en_US/translations.ts
  source/static/whatsNew/2.0.0.json
  source/static/whatsNew/2.0.1.json
  source/static/whatsNew/2.0.2.json
  source/static/whatsNew/2.0.3.json
  source/static/whatsNew/2.0.4.json
  source/static/whatsNew/2.0.5.json
Labels: dev-improvement

#1787 Fix crash when navigating back from the actor view to the movie detail view
  components/manager/QueueManager.bs
Labels: bug-fix

#1756 Add setting to hide community and critical ratings for movies
  components/ItemGrid/MovieLibraryView.bs
  components/movies/MovieDetails.bs
  components/movies/MovieDetails.xml
  locale/en_US/translations.ts
  settings/settings.json
Labels: new-setting
