Repository jellyfin/jellyfin-roku, pull requests merged in 2024-02, with the labels that each got.

#1678 Fix playback of additional parts
  source/Main.bs
Labels: bug-fix

#1688 Merge 2.0.3 into master
  Makefile
  components/ItemGrid/LoadVideoContentTask.bs
  manifest
  package.json
  source/Main.bs
  source/static/whatsNew/2.0.3.json
Labels: ignore-changelog

#1697 Fix in-process recording playback functionality. Prevent app crash when attempting to play in-process recordings.
  components/ItemGrid/LoadItemsTask2.bs
  components/ItemGrid/LoadVideoContentTask.bs
  components/data/HomeData.bs
  components/data/RecordingData.bs
  components/data/RecordingData.xml
  components/home/HomeItem.bs
  components/manager/QueueManager.bs
  source/Main.bs
  source/api/Items.bs
  source/utils/quickplay.bs
Labels: bug-fix

#1514 Remove overhang logo and user when viewing media
  components/JFOverhang.bs
  components/JFOverhang.xml
  components/config/LoginScene.bs
  components/config/LoginScene.xml
  components/config/SetServerScreen.bs
  components/config/SetServerScreen.xml
  components/data/SceneManager.bs
  components/home/Home.bs
  components/home/HomeRows.bs
  components/login/UserSelect.bs
  components/login/UserSelect.xml
  images/logo.png
  resources/branding/beta/logo.png
  resources/branding/release/logo.png
  source/Main.bs
  source/utils/misc.bs
Labels: general-improvement

#1698 Update whats new for 2.0.4
  source/static/whatsNew/2.0.4.json
Labels: ignore-changelog

#1699 Pull bugfix branch into master
  Makefile
  components/ItemGrid/LoadItemsTask2.bs
  components/ItemGrid/LoadVideoContentTask.bs
  components/data/HomeData.bs
  components/data/RecordingData.bs
  components/data/RecordingData.xml
  components/home/HomeItem.bs
  components/manager/QueueManager.bs
  manifest
  package-lock.json
  package.json
  source/Main.bs
  source/api/Items.bs
  source/static/whatsNew/2.0.4.json
  source/utils/quickplay.bs
Labels: ignore-changelog

#1644 Play song as part of album
  source/Main.bs
Labels: general-improvement

#1705 Prevent crash when homesection setting is invalid
  components/home/HomeRows.bs
Labels: bug-fix

#1707 Fix new version bump workflow
  .github/workflows/build-dev.yml
Labels: ignore-changelog

#1709 Use JF bot to create version bump PR
  .github/workflows/bump-version.yml
Labels: ignore-changelog

#1712 Fix sporadic crash on home screen
  components/home/HomeItem.bs
Labels: bug-fix

#1714 Fix sporadic crash when using ItemGrid
  components/ItemGrid/GridItem.bs
Labels: bug-fix

#1713 Fix sporadic home screen crash 2
  components/home/HomeItem.bs
Labels: bug-fix

#1718 Only show Next Episode button if there is a next episode
  components/video/VideoPlayerView.bs
Labels: bug-fix

#1720 Merge 2.0.5 into master
  Makefile
  components/ItemGrid/GridItem.bs
  components/home/HomeItem.bs
  components/home/HomeRows.bs
  components/video/VideoPlayerView.bs
  manifest
  package-lock.json
  package.json
  source/static/whatsNew/2.0.5.json
Labels: ignore-changelog

#1715 Create isChainValid() function to easily test property chains
  bsconfig-tdd-sample.json
  bsconfig-tests.json
  source/utils/misc.bs
  test-app/manifest
  test-app/source/tests/utils/misc/isAllValid.spec.bs
  test-app/source/tests/utils/misc/isChainValid.spec.bs
Labels: dev-improvement

#1703 Create method to navigate to Previous/Next items in playlist
  components/manager/QueueManager.bs
  components/manager/QueueManager.xml
  components/music/AudioPlayerView.bs
  components/video/OSD.bs
  components/video/OSD.xml
  components/video/VideoPlayerView.bs
  images/icons/itemNext.png
  images/icons/itemPrevious.png
Labels: new-feature, multi-part
